// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID           uuid.UUID          `json:"id"`
	OrgID        pgtype.UUID        `json:"org_id"`
	ProjectID    pgtype.UUID        `json:"project_id"`
	ActorAdminID pgtype.UUID        `json:"actor_admin_id"`
	Action       string             `json:"action"`
	TargetType   *string            `json:"target_type"`
	TargetID     pgtype.UUID        `json:"target_id"`
	Metadata     []byte             `json:"metadata"`
	IpAddress    *netip.Addr        `json:"ip_address"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type AuthExchangeCode struct {
	CodeHash   string             `json:"code_hash"`
	UserID     uuid.UUID          `json:"user_id"`
	ProjectID  uuid.UUID          `json:"project_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt pgtype.Timestamptz `json:"consumed_at"`
}

type ConsoleAdmin struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Disabled     bool               `json:"disabled"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type ConsoleSession struct {
	ID               uuid.UUID          `json:"id"`
	AdminID          uuid.UUID          `json:"admin_id"`
	RefreshTokenHash string             `json:"refresh_token_hash"`
	DeviceInfo       *string            `json:"device_info"`
	IpAddress        *netip.Addr        `json:"ip_address"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	LastUsedAt       pgtype.Timestamptz `json:"last_used_at"`
}

type OauthAccount struct {
	ID              uuid.UUID          `json:"id"`
	UserID          uuid.UUID          `json:"user_id"`
	Provider        string             `json:"provider"`
	ProviderUserID  string             `json:"provider_user_id"`
	AccessTokenEnc  *string            `json:"access_token_enc"`
	RefreshTokenEnc *string            `json:"refresh_token_enc"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type OauthState struct {
	State       string             `json:"state"`
	ProjectID   uuid.UUID          `json:"project_id"`
	Provider    string             `json:"provider"`
	RedirectUri string             `json:"redirect_uri"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

type OrgMembership struct {
	OrgID     uuid.UUID          `json:"org_id"`
	AdminID   uuid.UUID          `json:"admin_id"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Organization struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type OtpCode struct {
	ID          uuid.UUID          `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	ProjectID   uuid.UUID          `json:"project_id"`
	Destination string             `json:"destination"`
	CodeHash    string             `json:"code_hash"`
	Purpose     string             `json:"purpose"`
	Attempts    int16              `json:"attempts"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt  pgtype.Timestamptz `json:"consumed_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Permission struct {
	ID          uuid.UUID          `json:"id"`
	ProjectID   uuid.UUID          `json:"project_id"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Project struct {
	ID                         uuid.UUID          `json:"id"`
	OrgID                      uuid.UUID          `json:"org_id"`
	Name                       string             `json:"name"`
	Environment                string             `json:"environment"`
	ApiKey                     string             `json:"api_key"`
	ApiSecretHash              string             `json:"api_secret_hash"`
	AllowedOrigins             []string           `json:"allowed_origins"`
	OtpEnabled                 bool               `json:"otp_enabled"`
	GoogleOauthClientID        *string            `json:"google_oauth_client_id"`
	GoogleOauthClientSecretEnc *string            `json:"google_oauth_client_secret_enc"`
	GoogleOauthRedirectUri     *string            `json:"google_oauth_redirect_uri"`
	AccessTokenTtlSeconds      int32              `json:"access_token_ttl_seconds"`
	RefreshTokenTtlSeconds     int32              `json:"refresh_token_ttl_seconds"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
}

type RefreshTokenHistory struct {
	TokenHash string             `json:"token_hash"`
	SessionID uuid.UUID          `json:"session_id"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
}

type Role struct {
	ID          uuid.UUID          `json:"id"`
	ProjectID   uuid.UUID          `json:"project_id"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	IsDefault   bool               `json:"is_default"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type RolePermission struct {
	RoleID       uuid.UUID `json:"role_id"`
	PermissionID uuid.UUID `json:"permission_id"`
	ProjectID    uuid.UUID `json:"project_id"`
}

type Session struct {
	ID               uuid.UUID          `json:"id"`
	UserID           uuid.UUID          `json:"user_id"`
	RefreshTokenHash string             `json:"refresh_token_hash"`
	DeviceInfo       *string            `json:"device_info"`
	IpAddress        *netip.Addr        `json:"ip_address"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	LastUsedAt       pgtype.Timestamptz `json:"last_used_at"`
}

type User struct {
	ID            uuid.UUID          `json:"id"`
	ProjectID     uuid.UUID          `json:"project_id"`
	Email         *string            `json:"email"`
	Username      *string            `json:"username"`
	Phone         *string            `json:"phone"`
	PasswordHash  *string            `json:"password_hash"`
	EmailVerified bool               `json:"email_verified"`
	PhoneVerified bool               `json:"phone_verified"`
	Banned        bool               `json:"banned"`
	Metadata      []byte             `json:"metadata"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type UserRole struct {
	UserID    uuid.UUID `json:"user_id"`
	RoleID    uuid.UUID `json:"role_id"`
	ProjectID uuid.UUID `json:"project_id"`
}
