// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oauth.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAuthExchangeCode = `-- name: CreateAuthExchangeCode :exec
INSERT INTO auth_exchange_codes (code_hash, user_id, project_id, expires_at)
VALUES ($1, $2, $3, $4)
`

type CreateAuthExchangeCodeParams struct {
	CodeHash  string             `json:"code_hash"`
	UserID    uuid.UUID          `json:"user_id"`
	ProjectID uuid.UUID          `json:"project_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateAuthExchangeCode(ctx context.Context, arg CreateAuthExchangeCodeParams) error {
	_, err := q.db.Exec(ctx, createAuthExchangeCode,
		arg.CodeHash,
		arg.UserID,
		arg.ProjectID,
		arg.ExpiresAt,
	)
	return err
}

const createOAuthAccount = `-- name: CreateOAuthAccount :one
INSERT INTO oauth_accounts (user_id, provider, provider_user_id, access_token_enc, refresh_token_enc)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, provider, provider_user_id, access_token_enc, refresh_token_enc, created_at
`

type CreateOAuthAccountParams struct {
	UserID          uuid.UUID `json:"user_id"`
	Provider        string    `json:"provider"`
	ProviderUserID  string    `json:"provider_user_id"`
	AccessTokenEnc  *string   `json:"access_token_enc"`
	RefreshTokenEnc *string   `json:"refresh_token_enc"`
}

func (q *Queries) CreateOAuthAccount(ctx context.Context, arg CreateOAuthAccountParams) (OauthAccount, error) {
	row := q.db.QueryRow(ctx, createOAuthAccount,
		arg.UserID,
		arg.Provider,
		arg.ProviderUserID,
		arg.AccessTokenEnc,
		arg.RefreshTokenEnc,
	)
	var i OauthAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.AccessTokenEnc,
		&i.RefreshTokenEnc,
		&i.CreatedAt,
	)
	return i, err
}

const createOAuthState = `-- name: CreateOAuthState :exec
INSERT INTO oauth_states (state, project_id, provider, redirect_uri, expires_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateOAuthStateParams struct {
	State       string             `json:"state"`
	ProjectID   uuid.UUID          `json:"project_id"`
	Provider    string             `json:"provider"`
	RedirectUri string             `json:"redirect_uri"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateOAuthState(ctx context.Context, arg CreateOAuthStateParams) error {
	_, err := q.db.Exec(ctx, createOAuthState,
		arg.State,
		arg.ProjectID,
		arg.Provider,
		arg.RedirectUri,
		arg.ExpiresAt,
	)
	return err
}

const deleteExpiredAuthExchangeCodes = `-- name: DeleteExpiredAuthExchangeCodes :exec
DELETE FROM auth_exchange_codes WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredAuthExchangeCodes(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredAuthExchangeCodes)
	return err
}

const deleteExpiredOAuthStates = `-- name: DeleteExpiredOAuthStates :exec
DELETE FROM oauth_states WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredOAuthStates(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredOAuthStates)
	return err
}

const getOAuthAccount = `-- name: GetOAuthAccount :one
SELECT id, user_id, provider, provider_user_id, access_token_enc, refresh_token_enc, created_at FROM oauth_accounts WHERE provider = $1 AND provider_user_id = $2
`

type GetOAuthAccountParams struct {
	Provider       string `json:"provider"`
	ProviderUserID string `json:"provider_user_id"`
}

func (q *Queries) GetOAuthAccount(ctx context.Context, arg GetOAuthAccountParams) (OauthAccount, error) {
	row := q.db.QueryRow(ctx, getOAuthAccount, arg.Provider, arg.ProviderUserID)
	var i OauthAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.AccessTokenEnc,
		&i.RefreshTokenEnc,
		&i.CreatedAt,
	)
	return i, err
}

const takeAuthExchangeCode = `-- name: TakeAuthExchangeCode :one
UPDATE auth_exchange_codes SET consumed_at = now()
WHERE code_hash = $1 AND project_id = $2 AND consumed_at IS NULL AND expires_at > now()
RETURNING code_hash, user_id, project_id, created_at, expires_at, consumed_at
`

type TakeAuthExchangeCodeParams struct {
	CodeHash  string    `json:"code_hash"`
	ProjectID uuid.UUID `json:"project_id"`
}

// Atomically consume: only an unexpired, unconsumed code for this project returns.
func (q *Queries) TakeAuthExchangeCode(ctx context.Context, arg TakeAuthExchangeCodeParams) (AuthExchangeCode, error) {
	row := q.db.QueryRow(ctx, takeAuthExchangeCode, arg.CodeHash, arg.ProjectID)
	var i AuthExchangeCode
	err := row.Scan(
		&i.CodeHash,
		&i.UserID,
		&i.ProjectID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return i, err
}

const takeOAuthState = `-- name: TakeOAuthState :one
DELETE FROM oauth_states WHERE state = $1 RETURNING state, project_id, provider, redirect_uri, created_at, expires_at
`

// Single-use: the row is deleted as it's read.
func (q *Queries) TakeOAuthState(ctx context.Context, state string) (OauthState, error) {
	row := q.db.QueryRow(ctx, takeOAuthState, state)
	var i OauthState
	err := row.Scan(
		&i.State,
		&i.ProjectID,
		&i.Provider,
		&i.RedirectUri,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
