// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: otp.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const consumeOTP = `-- name: ConsumeOTP :exec
UPDATE otp_codes SET consumed_at = now() WHERE id = $1
`

func (q *Queries) ConsumeOTP(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, consumeOTP, id)
	return err
}

const createOTP = `-- name: CreateOTP :one
INSERT INTO otp_codes (project_id, destination, code_hash, purpose, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, project_id, destination, code_hash, purpose, attempts, expires_at, consumed_at, created_at
`

type CreateOTPParams struct {
	ProjectID   uuid.UUID          `json:"project_id"`
	Destination string             `json:"destination"`
	CodeHash    string             `json:"code_hash"`
	Purpose     string             `json:"purpose"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

// user_id is left NULL at creation; the account is resolved (login) or created
// (signup) at verify time from `destination`.
func (q *Queries) CreateOTP(ctx context.Context, arg CreateOTPParams) (OtpCode, error) {
	row := q.db.QueryRow(ctx, createOTP,
		arg.ProjectID,
		arg.Destination,
		arg.CodeHash,
		arg.Purpose,
		arg.ExpiresAt,
	)
	var i OtpCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.Destination,
		&i.CodeHash,
		&i.Purpose,
		&i.Attempts,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredOTPs = `-- name: DeleteExpiredOTPs :exec
DELETE FROM otp_codes WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredOTPs(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredOTPs)
	return err
}

const getLatestOTPCreatedAt = `-- name: GetLatestOTPCreatedAt :one
SELECT created_at FROM otp_codes
WHERE project_id = $1 AND destination = $2 AND purpose = $3
ORDER BY created_at DESC
LIMIT 1
`

type GetLatestOTPCreatedAtParams struct {
	ProjectID   uuid.UUID `json:"project_id"`
	Destination string    `json:"destination"`
	Purpose     string    `json:"purpose"`
}

// Resend throttle.
func (q *Queries) GetLatestOTPCreatedAt(ctx context.Context, arg GetLatestOTPCreatedAtParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getLatestOTPCreatedAt, arg.ProjectID, arg.Destination, arg.Purpose)
	var created_at pgtype.Timestamptz
	err := row.Scan(&created_at)
	return created_at, err
}

const getOTPByID = `-- name: GetOTPByID :one
SELECT id, user_id, project_id, destination, code_hash, purpose, attempts, expires_at, consumed_at, created_at FROM otp_codes WHERE id = $1
`

func (q *Queries) GetOTPByID(ctx context.Context, id uuid.UUID) (OtpCode, error) {
	row := q.db.QueryRow(ctx, getOTPByID, id)
	var i OtpCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.Destination,
		&i.CodeHash,
		&i.Purpose,
		&i.Attempts,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const incrementOTPAttempts = `-- name: IncrementOTPAttempts :one
UPDATE otp_codes SET attempts = attempts + 1 WHERE id = $1 RETURNING attempts
`

func (q *Queries) IncrementOTPAttempts(ctx context.Context, id uuid.UUID) (int16, error) {
	row := q.db.QueryRow(ctx, incrementOTPAttempts, id)
	var attempts int16
	err := row.Scan(&attempts)
	return attempts, err
}

const invalidateActiveOTPs = `-- name: InvalidateActiveOTPs :exec
UPDATE otp_codes SET consumed_at = now()
WHERE project_id = $1 AND destination = $2 AND purpose = $3 AND consumed_at IS NULL
`

type InvalidateActiveOTPsParams struct {
	ProjectID   uuid.UUID `json:"project_id"`
	Destination string    `json:"destination"`
	Purpose     string    `json:"purpose"`
}

// Burn any earlier un-consumed codes for this destination+purpose before a new
// one is issued, so only the most recent code can ever verify.
func (q *Queries) InvalidateActiveOTPs(ctx context.Context, arg InvalidateActiveOTPsParams) error {
	_, err := q.db.Exec(ctx, invalidateActiveOTPs, arg.ProjectID, arg.Destination, arg.Purpose)
	return err
}
