// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getProjectByAPIKey = `-- name: GetProjectByAPIKey :one
SELECT id, org_id, name, environment, api_key, api_secret_hash, allowed_origins, otp_enabled, google_oauth_client_id, google_oauth_client_secret_enc, google_oauth_redirect_uri, access_token_ttl_seconds, refresh_token_ttl_seconds, created_at, updated_at FROM projects WHERE api_key = $1
`

// Hottest lookup in the system: every end-user request resolves its project
// from the X-API-Key header before anything else.
func (q *Queries) GetProjectByAPIKey(ctx context.Context, apiKey string) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByAPIKey, apiKey)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Environment,
		&i.ApiKey,
		&i.ApiSecretHash,
		&i.AllowedOrigins,
		&i.OtpEnabled,
		&i.GoogleOauthClientID,
		&i.GoogleOauthClientSecretEnc,
		&i.GoogleOauthRedirectUri,
		&i.AccessTokenTtlSeconds,
		&i.RefreshTokenTtlSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, org_id, name, environment, api_key, api_secret_hash, allowed_origins, otp_enabled, google_oauth_client_id, google_oauth_client_secret_enc, google_oauth_redirect_uri, access_token_ttl_seconds, refresh_token_ttl_seconds, created_at, updated_at FROM projects WHERE id = $1
`

func (q *Queries) GetProjectByID(ctx context.Context, id uuid.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Environment,
		&i.ApiKey,
		&i.ApiSecretHash,
		&i.AllowedOrigins,
		&i.OtpEnabled,
		&i.GoogleOauthClientID,
		&i.GoogleOauthClientSecretEnc,
		&i.GoogleOauthRedirectUri,
		&i.AccessTokenTtlSeconds,
		&i.RefreshTokenTtlSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
