// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, refresh_token_hash, device_info, ip_address, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, refresh_token_hash, device_info, ip_address, expires_at, revoked_at, created_at, last_used_at
`

type CreateSessionParams struct {
	UserID           uuid.UUID          `json:"user_id"`
	RefreshTokenHash string             `json:"refresh_token_hash"`
	DeviceInfo       *string            `json:"device_info"`
	IpAddress        *netip.Addr        `json:"ip_address"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.RefreshTokenHash,
		arg.DeviceInfo,
		arg.IpAddress,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.DeviceInfo,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const findSessionByUsedRefreshHash = `-- name: FindSessionByUsedRefreshHash :one
SELECT session_id FROM refresh_token_history WHERE token_hash = $1
`

// A hit here means a rotated-away token was replayed -> reuse detected.
func (q *Queries) FindSessionByUsedRefreshHash(ctx context.Context, tokenHash string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, findSessionByUsedRefreshHash, tokenHash)
	var session_id uuid.UUID
	err := row.Scan(&session_id)
	return session_id, err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, user_id, refresh_token_hash, device_info, ip_address, expires_at, revoked_at, created_at, last_used_at FROM sessions WHERE id = $1
`

func (q *Queries) GetSessionByID(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.DeviceInfo,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getSessionByRefreshHash = `-- name: GetSessionByRefreshHash :one
SELECT id, user_id, refresh_token_hash, device_info, ip_address, expires_at, revoked_at, created_at, last_used_at FROM sessions WHERE refresh_token_hash = $1
`

// Hot path for POST /auth/refresh.
func (q *Queries) GetSessionByRefreshHash(ctx context.Context, refreshTokenHash string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByRefreshHash, refreshTokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.DeviceInfo,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const recordUsedRefreshHash = `-- name: RecordUsedRefreshHash :exec
INSERT INTO refresh_token_history (token_hash, session_id)
VALUES ($1, $2)
ON CONFLICT (token_hash) DO NOTHING
`

type RecordUsedRefreshHashParams struct {
	TokenHash string    `json:"token_hash"`
	SessionID uuid.UUID `json:"session_id"`
}

// Called on every rotation with the outgoing hash.
func (q *Queries) RecordUsedRefreshHash(ctx context.Context, arg RecordUsedRefreshHashParams) error {
	_, err := q.db.Exec(ctx, recordUsedRefreshHash, arg.TokenHash, arg.SessionID)
	return err
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :exec
UPDATE sessions SET revoked_at = now() WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllUserSessions(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllUserSessions, userID)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions SET revoked_at = now() WHERE id = $1
`

func (q *Queries) RevokeSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeSession, id)
	return err
}

const rotateSessionRefreshHash = `-- name: RotateSessionRefreshHash :one
UPDATE sessions
SET refresh_token_hash = $1,
    expires_at         = $2,
    last_used_at        = now()
WHERE id = $3 AND revoked_at IS NULL
RETURNING id, user_id, refresh_token_hash, device_info, ip_address, expires_at, revoked_at, created_at, last_used_at
`

type RotateSessionRefreshHashParams struct {
	NewHash   string             `json:"new_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	ID        uuid.UUID          `json:"id"`
}

// Refresh-token rotation: swap in the new hash, bump usage, extend expiry.
func (q *Queries) RotateSessionRefreshHash(ctx context.Context, arg RotateSessionRefreshHashParams) (Session, error) {
	row := q.db.QueryRow(ctx, rotateSessionRefreshHash, arg.NewHash, arg.ExpiresAt, arg.ID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.DeviceInfo,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}
