// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (project_id, email, username, phone, password_hash)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, project_id, email, username, phone, password_hash, email_verified, phone_verified, banned, metadata, created_at, updated_at
`

type CreateUserParams struct {
	ProjectID    uuid.UUID `json:"project_id"`
	Email        *string   `json:"email"`
	Username     *string   `json:"username"`
	Phone        *string   `json:"phone"`
	PasswordHash *string   `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ProjectID,
		arg.Email,
		arg.Username,
		arg.Phone,
		arg.PasswordHash,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Email,
		&i.Username,
		&i.Phone,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.PhoneVerified,
		&i.Banned,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, project_id, email, username, phone, password_hash, email_verified, phone_verified, banned, metadata, created_at, updated_at FROM users WHERE project_id = $1 AND email = $2
`

type GetUserByEmailParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Email     *string   `json:"email"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, arg.ProjectID, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Email,
		&i.Username,
		&i.Phone,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.PhoneVerified,
		&i.Banned,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, project_id, email, username, phone, password_hash, email_verified, phone_verified, banned, metadata, created_at, updated_at FROM users WHERE id = $1 AND project_id = $2
`

type GetUserByIDParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) GetUserByID(ctx context.Context, arg GetUserByIDParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, arg.ID, arg.ProjectID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Email,
		&i.Username,
		&i.Phone,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.PhoneVerified,
		&i.Banned,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByIDOnly = `-- name: GetUserByIDOnly :one
SELECT id, project_id, email, username, phone, password_hash, email_verified, phone_verified, banned, metadata, created_at, updated_at FROM users WHERE id = $1
`

// id is globally unique; project_id comes back on the row.
func (q *Queries) GetUserByIDOnly(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByIDOnly, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Email,
		&i.Username,
		&i.Phone,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.PhoneVerified,
		&i.Banned,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByLogin = `-- name: GetUserByLogin :one
SELECT id, project_id, email, username, phone, password_hash, email_verified, phone_verified, banned, metadata, created_at, updated_at FROM users
WHERE project_id = $1
  AND (email = $2 OR username = $2)
LIMIT 1
`

type GetUserByLoginParams struct {
	ProjectID  uuid.UUID `json:"project_id"`
	Identifier *string   `json:"identifier"`
}

// Resolves the /auth/login "email_or_username" field within a project.
func (q *Queries) GetUserByLogin(ctx context.Context, arg GetUserByLoginParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByLogin, arg.ProjectID, arg.Identifier)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Email,
		&i.Username,
		&i.Phone,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.PhoneVerified,
		&i.Banned,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setUserBanned = `-- name: SetUserBanned :exec
UPDATE users SET banned = $2 WHERE id = $1 AND project_id = $3
`

type SetUserBannedParams struct {
	ID        uuid.UUID `json:"id"`
	Banned    bool      `json:"banned"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) SetUserBanned(ctx context.Context, arg SetUserBannedParams) error {
	_, err := q.db.Exec(ctx, setUserBanned, arg.ID, arg.Banned, arg.ProjectID)
	return err
}

const setUserEmailVerified = `-- name: SetUserEmailVerified :exec
UPDATE users SET email_verified = true WHERE id = $1
`

func (q *Queries) SetUserEmailVerified(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, setUserEmailVerified, id)
	return err
}

const setUserPasswordHash = `-- name: SetUserPasswordHash :exec
UPDATE users SET password_hash = $2 WHERE id = $1
`

type SetUserPasswordHashParams struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash *string   `json:"password_hash"`
}

func (q *Queries) SetUserPasswordHash(ctx context.Context, arg SetUserPasswordHashParams) error {
	_, err := q.db.Exec(ctx, setUserPasswordHash, arg.ID, arg.PasswordHash)
	return err
}
